[package]
name = "ray-tracing"
version = "0.3.0"
edition = "2024"

[dependencies]
nalgebra = "0.33.2"
rand = "0.9.1"
rayon = "1.10.0"

[profile.release]
lto = "fat"
codegen-units = 1

[features]
benchmark = []
